export const EnumTranslations = {
  Gender: {
    MALE: "Masculino",
    FEMALE: "Feminino",
  },
  WorkoutType: {
    STRENGTH_TRAINING: "Treino de Força",
    HIIT: "HIIT",
    CARDIO: "Cardio",
    CROSSFIT: "Crossfit",
    CALISTHENICS: "Calistenia",
    PILATES: "Pilates",
    YOGA: "Yoga",
    FUNCTIONAL: "Funcional",
  },
  GoalStatus: {
    ACTIVE: "Ativo",
    PAUSED: "Pausado",
    COMPLETED: "Concluído",
    ABANDONED: "Abandonado",
  },
  FitnessGoal: {
    FAT_LOSS: "Perda de Gordura",
    MUSCLE_GAIN: "Ganho de Massa",
    BODY_RECOMPOSITION: "Recomposição Corporal",
    STRENGTH_GAIN: "Ganho de Força",
    ENDURANCE_IMPROVEMENT: "Melhoria de Resistência",
    INJURY_RECOVERY: "Recuperação de Lesão",
    POSTURE_CORRECTION: "Correção Postural",
    FUNCTIONAL_FITNESS: "Condicionamento Funcional",
    DEFINITION: "Definição Muscular",
    COMPETITION_PREP: "Preparação para Competição",
  },
  PhotoCategory: {
    FRONT: "Frente",
    SIDE: "Lateral",
    BACK: "Costas",
    FLEXED: "Contraído",
    RELAXED: "Relaxado",
  },
  TrainingFormat: {
    IN_PERSON: "Presencial",
    ONLINE: "Online",
    HYBRID: "Híbrido",
    NUTRITION_PLAN: "Plano Nutricional",
  },
  Status: {
    ACTIVE: "Ativo",
    INACTIVE: "Inativo",
    PENDING: "Pendente",
    COMPLETED: "Concluído",
    IN_PROGRESS: "Em Progresso",
    ON_HOLD: "Em Espera",
  },
  Role: {
    PERSONAL_TRAINER: "Personal Trainer",
    STUDENT: "Aluno",
  },
  SessionStatus: {
    SCHEDULED: "Agendada",
    CONFIRMED: "Confirmada",
    IN_PROGRESS: "Em Andamento",
    COMPLETED: "Concluída",
    CANCELED: "Cancelada",
    MISSED: "Não Compareceu",
  },
  SessionType: {
    PERSONAL_TRAINING: "Treino Personalizado",
    NUTRITION: "Nutrição",
    ASSESSMENT: "Avaliação",
    FOLLOW_UP: "Acompanhamento",
  },
  AttachmentType: {
    EXERCISE_LIST: "Lista de Exercícios",
    DIET_PLAN: "Plano Alimentar",
    PROGRESS_PHOTO: "Foto de Progresso",
    NOTE: "Anotação",
  },
  RecurrencePattern: {
    DAILY: "Diário",
    WEEKLY: "Semanal",
    BIWEEKLY: "Quinzenal",
    MONTHLY: "Mensal",
    CUSTOM: "Personalizado",
  },
  DayOfWeek: {
    MONDAY: "Segunda",
    TUESDAY: "Terça",
    WEDNESDAY: "Quarta",
    THURSDAY: "Quinta",
    FRIDAY: "Sexta",
    SATURDAY: "Sábado",
    SUNDAY: "Domingo",
  },
  DifficultyLevel: {
    BEGINNER: "Iniciante",
    INTERMEDIATE: "Intermediário",
    ADVANCED: "Avançado",
  },
  MuscleGroup: {
    CHEST: "Peitoral",
    UPPER_CHEST: "Peitoral Superior",
    LOWER_CHEST: "Peitoral Inferior",
    BACK: "Costas",
    LATS: "Latíssimo do Dorso",
    TRAPS: "Trapézio",
    RHOMBOIDS: "Romboides",
    LOWER_BACK: "Lombar",
    SHOULDERS: "Ombros",
    FRONT_DELTS: "Deltóide Anterior",
    SIDE_DELTS: "Deltóide Lateral",
    REAR_DELTS: "Deltóide Posterior",
    BICEPS: "Bíceps",
    TRICEPS: "Tríceps",
    FOREARMS: "Antebraços",
    ABS: "Abdômen",
    OBLIQUES: "Oblíquos",
    TRANSVERSE_ABS: "Transverso do Abdômen",
    ERECTORS: "Eretores da Espinha",
    QUADS: "Quadríceps",
    HAMSTRINGS: "Isquiotibiais",
    GLUTES: "Glúteos",
    ADDUCTORS: "Adutores",
    ABDUCTORS: "Abdutores",
    CALVES: "Panturrilhas",
    TIBIALIS: "Tibial Anterior",
    FULL_BODY: "Corpo Inteiro",
    CARDIO: "Cardio",
    POSTERIOR_CHAIN: "Cadeia Posterior",
  },
} as const;

export const SelectOptions = {
  Gender: [
    { value: "MALE", label: "Masculino" },
    { value: "FEMALE", label: "Feminino" },
  ],
  WorkoutType: [
    { value: "STRENGTH_TRAINING", label: "Treino de Força" },
    { value: "HIIT", label: "HIIT" },
    { value: "CARDIO", label: "Cardio" },
    { value: "CROSSFIT", label: "Crossfit" },
    { value: "CALISTHENICS", label: "Calistenia" },
    { value: "PILATES", label: "Pilates" },
    { value: "YOGA", label: "Yoga" },
    { value: "FUNCTIONAL", label: "Funcional" },
  ],
  GoalStatus: [
    { value: "ACTIVE", label: "Ativo" },
    { value: "PAUSED", label: "Pausado" },
    { value: "COMPLETED", label: "Concluído" },
    { value: "ABANDONED", label: "Abandonado" },
  ],
  FitnessGoal: [
    { value: "FAT_LOSS", label: "Perda de Gordura" },
    { value: "MUSCLE_GAIN", label: "Ganho de Massa" },
    { value: "BODY_RECOMPOSITION", label: "Recomposição Corporal" },
    { value: "STRENGTH_GAIN", label: "Ganho de Força" },
    { value: "ENDURANCE_IMPROVEMENT", label: "Melhoria de Resistência" },
    { value: "INJURY_RECOVERY", label: "Recuperação de Lesão" },
    { value: "POSTURE_CORRECTION", label: "Correção Postural" },
    { value: "FUNCTIONAL_FITNESS", label: "Condicionamento Funcional" },
    { value: "DEFINITION", label: "Definição Muscular" },
    { value: "COMPETITION_PREP", label: "Preparação para Competição" },
  ],
  PhotoCategory: [
    { value: "FRONT", label: "Frente" },
    { value: "SIDE", label: "Lateral" },
    { value: "BACK", label: "Costas" },
    { value: "FLEXED", label: "Contraído" },
    { value: "RELAXED", label: "Relaxado" },
  ],
  TrainingFormat: [
    { value: "IN_PERSON", label: "Presencial" },
    { value: "ONLINE", label: "Online" },
    { value: "HYBRID", label: "Híbrido" },
    { value: "NUTRITION_PLAN", label: "Plano Nutricional" },
  ],
  Status: [
    { value: "ACTIVE", label: "Ativo" },
    { value: "INACTIVE", label: "Inativo" },
    { value: "PENDING", label: "Pendente" },
    { value: "COMPLETED", label: "Concluído" },
    { value: "IN_PROGRESS", label: "Em Progresso" },
    { value: "ON_HOLD", label: "Em Espera" },
  ],
  Role: [
    { value: "PERSONAL_TRAINER", label: "Personal Trainer" },
    { value: "STUDENT", label: "Aluno" },
  ],
  SessionStatus: [
    { value: "SCHEDULED", label: "Agendada" },
    { value: "CONFIRMED", label: "Confirmada" },
    { value: "IN_PROGRESS", label: "Em Andamento" },
    { value: "COMPLETED", label: "Concluída" },
    { value: "CANCELED", label: "Cancelada" },
    { value: "MISSED", label: "Não Compareceu" },
  ],
  SessionType: [
    { value: "PERSONAL_TRAINING", label: "Treino Personalizado" },
    { value: "NUTRITION", label: "Nutrição" },
    { value: "ASSESSMENT", label: "Avaliação" },
    { value: "FOLLOW_UP", label: "Acompanhamento" },
  ],
  AttachmentType: [
    { value: "EXERCISE_LIST", label: "Lista de Exercícios" },
    { value: "DIET_PLAN", label: "Plano Alimentar" },
    { value: "PROGRESS_PHOTO", label: "Foto de Progresso" },
    { value: "NOTE", label: "Anotação" },
  ],
  RecurrencePattern: [
    { value: "DAILY", label: "Diário" },
    { value: "WEEKLY", label: "Semanal" },
    { value: "BIWEEKLY", label: "Quinzenal" },
    { value: "MONTHLY", label: "Mensal" },
    { value: "CUSTOM", label: "Personalizado" },
  ],
  DayOfWeek: [
    { value: "MONDAY", label: "Segunda" },
    { value: "TUESDAY", label: "Terça" },
    { value: "WEDNESDAY", label: "Quarta" },
    { value: "THURSDAY", label: "Quinta" },
    { value: "FRIDAY", label: "Sexta" },
    { value: "SATURDAY", label: "Sábado" },
    { value: "SUNDAY", label: "Domingo" },
  ],
  DifficultyLevel: [
    { value: "BEGINNER", label: "Iniciante" },
    { value: "INTERMEDIATE", label: "Intermediário" },
    { value: "ADVANCED", label: "Avançado" },
  ],
  MuscleGroup: [
    { value: "CHEST", label: "Peitoral" },
    { value: "UPPER_CHEST", label: "Peitoral Superior" },
    { value: "LOWER_CHEST", label: "Peitoral Inferior" },
    { value: "BACK", label: "Costas" },
    { value: "LATS", label: "Latíssimo do Dorso" },
    { value: "TRAPS", label: "Trapézio" },
    { value: "RHOMBOIDS", label: "Romboides" },
    { value: "LOWER_BACK", label: "Lombar" },
    { value: "SHOULDERS", label: "Ombros" },
    { value: "FRONT_DELTS", label: "Deltóide Anterior" },
    { value: "SIDE_DELTS", label: "Deltóide Lateral" },
    { value: "REAR_DELTS", label: "Deltóide Posterior" },
    { value: "BICEPS", label: "Bíceps" },
    { value: "TRICEPS", label: "Tríceps" },
    { value: "FOREARMS", label: "Antebraços" },
    { value: "ABS", label: "Abdômen" },
    { value: "OBLIQUES", label: "Oblíquos" },
    { value: "TRANSVERSE_ABS", label: "Transverso do Abdômen" },
    { value: "ERECTORS", label: "Eretores da Espinha" },
    { value: "QUADS", label: "Quadríceps" },
    { value: "HAMSTRINGS", label: "Isquiotibiais" },
    { value: "GLUTES", label: "Glúteos" },
    { value: "ADDUCTORS", label: "Adutores" },
    { value: "ABDUCTORS", label: "Abdutores" },
    { value: "CALVES", label: "Panturrilhas" },
    { value: "TIBIALIS", label: "Tibial Anterior" },
    { value: "FULL_BODY", label: "Corpo Inteiro" },
    { value: "CARDIO", label: "Cardio" },
    { value: "POSTERIOR_CHAIN", label: "Cadeia Posterior" },
  ],
};

export const StatusColor = {
  ACTIVE: "#4CAF50",
  INACTIVE: "#9E9E9E",
  PENDING: "#FFC107",
  COMPLETED: "#2196F3",
  IN_PROGRESS: "#FF9800",
  ON_HOLD: "#607D8B",
} as const;
