export const EnumTranslations = {
  Gender: {
    MALE: "Masculino",
    FEMALE: "Feminino",
  },
  WorkoutType: {
    STRENGTH_TRAINING: "Treino de Força",
    HIIT: "HIIT",
    CARDIO: "Cardio",
    CROSSFIT: "Crossfit",
    CALISTHENICS: "Calistenia",
    PILATES: "Pilates",
    YOGA: "Yoga",
    FUNCTIONAL: "Funcional",
  },
  GoalStatus: {
    ACTIVE: "Ativo",
    PAUSED: "Pausado",
    COMPLETED: "Concluído",
    ABANDONED: "Abandonado",
  },
  FitnessGoal: {
    FAT_LOSS: "Perda de Gordura",
    MUSCLE_GAIN: "Ganho de Massa",
    BODY_RECOMPOSITION: "Recomposição Corporal",
    STRENGTH_GAIN: "Ganho de Força",
    ENDURANCE_IMPROVEMENT: "Melhoria de Resistência",
    INJURY_RECOVERY: "Recuperação de Lesão",
    POSTURE_CORRECTION: "Correção Postural",
    FUNCTIONAL_FITNESS: "Condicionamento Funcional",
    DEFINITION: "Definição Muscular",
    COMPETITION_PREP: "Preparação para Competição",
  },
  PhotoCategory: {
    FRONT: "Frente",
    SIDE: "Lateral",
    BACK: "Costas",
    FLEXED: "Contraído",
    RELAXED: "Relaxado",
  },
  TrainingFormat: {
    IN_PERSON: "Presencial",
    ONLINE: "Online",
    HYBRID: "Híbrido",
    NUTRITION_PLAN: "Plano Nutricional",
  },
  Status: {
    ACTIVE: "Ativo",
    INACTIVE: "Inativo",
    PENDING: "Pendente",
    COMPLETED: "Concluído",
    IN_PROGRESS: "Em Progresso",
    ON_HOLD: "Em Espera",
  },
  Role: {
    PERSONAL_TRAINER: "Personal Trainer",
    STUDENT: "Aluno",
  },
  SessionStatus: {
    SCHEDULED: "Agendada",
    CONFIRMED: "Confirmada",
    IN_PROGRESS: "Em Andamento",
    COMPLETED: "Concluída",
    CANCELED: "Cancelada",
    MISSED: "Não Compareceu",
  },
  SessionType: {
    PERSONAL_TRAINING: "Treino Personalizado",
    NUTRITION: "Nutrição",
    ASSESSMENT: "Avaliação",
    FOLLOW_UP: "Acompanhamento",
  },
  AttachmentType: {
    EXERCISE_LIST: "Lista de Exercícios",
    DIET_PLAN: "Plano Alimentar",
    PROGRESS_PHOTO: "Foto de Progresso",
    NOTE: "Anotação",
  },
  RecurrencePattern: {
    DAILY: "Diário",
    WEEKLY: "Semanal",
    BIWEEKLY: "Quinzenal",
    MONTHLY: "Mensal",
    CUSTOM: "Personalizado",
  },
  DayOfWeek: {
    MONDAY: "Segunda",
    TUESDAY: "Terça",
    WEDNESDAY: "Quarta",
    THURSDAY: "Quinta",
    FRIDAY: "Sexta",
    SATURDAY: "Sábado",
    SUNDAY: "Domingo",
  },
  DifficultyLevel: {
    BEGINNER: "Iniciante",
    INTERMEDIATE: "Intermediário",
    ADVANCED: "Avançado",
  },
  MuscleGroup: {
    CHEST: "Peitoral",
    UPPER_CHEST: "Peitoral Superior",
    LOWER_CHEST: "Peitoral Inferior",
    BACK: "Costas",
    LATS: "Latíssimo do Dorso",
    TRAPS: "Trapézio",
    RHOMBOIDS: "Romboides",
    LOWER_BACK: "Lombar",
    SHOULDERS: "Ombros",
    FRONT_DELTS: "Deltóide Anterior",
    SIDE_DELTS: "Deltóide Lateral",
    REAR_DELTS: "Deltóide Posterior",
    BICEPS: "Bíceps",
    TRICEPS: "Tríceps",
    FOREARMS: "Antebraços",
    ABS: "Abdômen",
    OBLIQUES: "Oblíquos",
    TRANSVERSE_ABS: "Transverso do Abdômen",
    ERECTORS: "Eretores da Espinha",
    QUADS: "Quadríceps",
    HAMSTRINGS: "Isquiotibiais",
    GLUTES: "Glúteos",
    ADDUCTORS: "Adutores",
    ABDUCTORS: "Abdutores",
    CALVES: "Panturrilhas",
    TIBIALIS: "Tibial Anterior",
    FULL_BODY: "Corpo Inteiro",
    CARDIO: "Cardio",
    POSTERIOR_CHAIN: "Cadeia Posterior",
  },
} as const;

// Tipagem para autocompletar
type TranslatedEnum = typeof EnumTranslations;
